version: '2.3'
services:
  mongodb:
    container_name: mongodb
    image: 'amd64/mongo'
    entrypoint:
        - mongod
        - --bind_ip_all
    ports:
      - 27017:27017
    networks:
      - front_agora
  mongo_data:
    container_name: mongo_data
    image: 'sagebionetworks/agora-mongo_data'
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - front_agora
  mongo_seed_links:
    container_name: mongo_seed_links
    image: 'sagebionetworks/agora-mongo_seed_links'
    links:
      - mongodb
    depends_on:
      - mongo_data
    networks:
      - front_agora
  mongo_seed_info:
    container_name: mongo_seed_info
    image: 'sagebionetworks/agora-mongo_seed_info'
    links:
      - mongodb
    depends_on:
      - mongo_seed_links
    networks:
      - front_agora
  mongo_seed_team:
    container_name: mongo_seed_team
    image: 'sagebionetworks/agora-mongo_seed_team'
    links:
      - mongodb
    depends_on:
      - mongo_seed_info
    networks:
      - front_agora
  mongo_seed_team_images:
    container_name: mongo_seed_team_images
    image: 'sagebionetworks/agora-mongo_seed_team_images'
    links:
      - mongodb
    depends_on:
      - mongo_seed_team
    networks:
      - front_agora

networks:
  front_agora:
    driver: bridge
    name: agora_network
